<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>com.kge.platform</groupId>
		<artifactId>framework-dependenices</artifactId>
		<version>1.1.0</version>
	</parent>

	<groupId>com.kge.energy</groupId>
	<artifactId>crm-service</artifactId>
	<version>1.1.0</version>
	<packaging>pom</packaging>

	<properties>
		<msg-api.version>1.0.0-SNAPSHOT</msg-api.version>
		<knife4j-openapi3-jakarta-spring-boot-starter.version>4.5.0</knife4j-openapi3-jakarta-spring-boot-starter.version>
		<!--sonar扫描插件-->
		<sonar-maven-plugin.version>5.0.0.4389</sonar-maven-plugin.version>
		<!--sonar需要扫描的文件-->
		<sonar.inclusions>**/*.java,**/*.xml</sonar.inclusions>
		<!--依赖漏洞检查插件-->
		<dependency-check-maven.version>12.0.0</dependency-check-maven.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.kge.energy</groupId>
				<artifactId>crm-infrastructure</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>com.kge.energy</groupId>
				<artifactId>crm-domain</artifactId>
				<version>${project.version}</version>
			</dependency>

			<dependency>
				<groupId>com.kge.energy</groupId>
				<artifactId>msg-api</artifactId>
				<version>${msg-api.version}</version>
			</dependency>

			<!-- Knife4j swagger增强在线接口文档 -->
			<dependency>
				<groupId>com.github.xiaoymin</groupId>
				<artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
				<version>${knife4j-openapi3-jakarta-spring-boot-starter.version}</version>
			</dependency>

		</dependencies>
	</dependencyManagement>

	<modules>
		<module>crm-infrastructure</module>
		<module>crm-domain</module>
		<module>crm-applet-provider</module>
		<module>crm-mgr-provider</module>
	</modules>

	<build>
		<plugins>
			<!-- SonarQube插件 -->
			<plugin>
				<groupId>org.sonarsource.scanner.maven</groupId>
				<artifactId>sonar-maven-plugin</artifactId>
				<version>${sonar-maven-plugin.version}</version>
			</plugin>
			<plugin>
				<groupId>org.owasp</groupId>
				<artifactId>dependency-check-maven</artifactId>
				<version>${dependency-check-maven.version}</version>
				<configuration>
					<format>ALL</format>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
