server:
  servlet:
    context-path: /applet

spring:
  profiles:
    active: @profileActive@

  application:
    name: crm-applet-provider

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.dbname:test}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      maximumPoolSize: 100 # 最大连接数
      minimumIdle: 5 # 最小空闲连接数
      idleTimeout: 60000 # 空闲连接超时时间（毫秒）
      maxLifetime: 1800000 # 连接最大生命周期（毫秒）
      connectionTimeout: 30000 # 获取连接超时时间（毫秒）
      autoCommit: true # 自动提交
      validationTimeout: 5000 # 连接验证超时时间（毫秒）
      leakDetectionThreshold: 180000 # 检测连接泄露的阈值（毫秒）
      isolateInternalQueries: false # 是否对内部查询使用独立的连接
      allowPoolSuspension: false # 是否允许暂停连接池
      readOnly: false # 连接是否只读
      connectionTestQuery: SELECT 1 # 测试连接是否可用的SQL

  data:
    redis:
      lettuce:
        pool:
          min-idle: 1

decorator:
  datasource:
    p6spy:
      log-format: "time:%(executionTime) || sql:%(sql)\n"
      logging: SLF4J
      custom-appender-class: com.p6spy.engine.spy.appender.Slf4JLogger

wechat:
  common:
    wxUrl: https://api.weixin.qq.com
  applet:
    appId: wx00c47c0f09ea4612
    appSecret: ee6576d61d20ba65286739ea977a6096
    orderStatusChangeTemplate: C6tY3sDufNBSUwczNpZGmt8c9DQWXkAUr0RQdXWDapE
    agencyOrderTemplate: TWbN4m8-ul8ibrD0NOIHZoIByCONasoq_ubNvSMGVoU
    feebackTemplate: Hr0ohb8bNSisQZIRSgEGjDCnCrYwlO6goOw2KaV-b74
    wxUrl: ${wechat.common.wxUrl}
    version: developer
    envVersion: developer
    agencyOrderPage: /pages/user/order/order
  official-account:
    appId: wxa3cbdc535f7b834b
    appSecret: ca7bd8b039847eb430b624a5158d816f
    wxUrl: ${wechat.common.wxUrl}


logging:
  config: classpath:config/logback.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: -1
      logic-not-delete-value: 1

auth:
  token:
    redis-front: ntcrm_test_token_
    white-list:
      - ${server.servlet.context-path}/doc.html
      - ${server.servlet.context-path}/webjars/**
      - ${server.servlet.context-path}/v3/api-docs/**
      - ${server.servlet.context-path}/wechat/login

epcpv:
  allregions: api/v1/pv/project/dim/regions
  allstages: api/v1/pv/project/dim/stages
  total: api/v1/pv/project/total
  capacitytotal: api/v1/pv/project/transformer/capacity/total
  regionstat: api/v1/pv/project/region/stat
  capacitystat: api/v1/pv/project/transformer/region/capacity/stat
  stagestat: api/v1/pv/project/stage/stat
  prolist: api/v1/pv/project/list
  inststat: api/v1/pv/project/inst/capacity/stat

# springdoc-openapi项目配置
springdoc:
  sys-name: 'E能管家-客户小程序API'
  author: '广州南方电力集团科技发展有限公司'
  version: 1.0.0
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: ${springdoc.sys-name}
      paths-to-match: '/**'
      packages-to-scan: com.kge.energy.crm
  default-flat-param-object: true

# knife4j的增强配置
knife4j:
  # 是否开启Knife4j增强模式
  enable: true
  # 是否开启一个默认的跨域配置,该功能配合自定义Host使用
  cors: false
  # 是否开启生产环境保护策略
  production: true
  setting:
    # Knife4j默认显示中文(zh-CN),如果想直接显示英文(en-US)，通过该配置进行设置即可
    language: zh-CN
    # 是否显示界面中SwaggerModel功能
    enable-swagger-models: true
    # 重命名SwaggerModel名称
    swagger-model-name: 实体类列表
    # 是否显示界面中"文档管理"功能
    enable-document-manage: true
    # 是否开启界面中对某接口的版本控制,如果开启，后端变化后Ui界面会存在小蓝点
    enable-version: true
    # 是否在每个Debug调试栏后显示刷新变量按钮,默认不显示
    enable-reload-cache-parameter: true
    # 调试Tab是否显示AfterScript功能,默认开启
    enable-after-script: true
    # 具体接口的过滤类型,默认为POST
    enable-filter-multipart-api-method-type: POST
    # 针对RequestMapping的接口请求类型,在不指定参数类型的情况下,如果不过滤,默认会显示7个类型的接口地址参数,如果开启此配置,默认展示一个Post类型的接口地址
    enable-filter-multipart-apis: false
    # 是否开启请求参数缓存，默认为true
    enable-request-cache: true
    # 是否启用Host
    enable-host: false
    # 启用Host后地址，如：192.168.0.1:8080
    enable-host-text: ""
    # 是否启用自定义主页内容，默认false
    enable-home-custom: false
    # 启用自定义主页内容后可以设置一个Markdown文件来自定义显示Home主页的显示内容
    home-custom-path: classpath:markdown/home.md
    # 是否启用搜索功能,默认值为true(代表开启搜索)，如果要禁用搜索，该值设为false
    enable-search: true
    # 禁用默认的Footer显示，如果要自定义的话该属性必须设置为false,否则不会生效
    enable-footer: false
    # 是否启用自定义Footer内容，默认false
    enable-footer-custom: true
    # 最终在Ui界面底部显示的Footer内容，支持Markdown格式
    footer-custom-content: Apache License 2.0 | Copyright  2024 - ${springdoc.contact}
    # 开启动态请求参数，true-开启，false-关闭
    enable-dynamic-parameter: true
    # 否启用调试功能,默认值为true(代表开启调试)，如果要禁用调试，该值设为false
    enable-debug: true
    # 是否启用OpenAPI功能,默认值为true(代表开启OpenAPI显示)，如果要禁用OpenAPI显示，该值设为false(需要注意的是如果开发者直接禁用调试，那么OpenAPI默认也是不显示的)
    enable-open-api: true
    enable-group: true
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: admin
    # Basic认证密码
    password: Kge@2024!

file:
  upload:
    allow-types: jpg,jpeg,png,pdf
    upload-url: http://172.18.26.112:80/fileservice/resourceManage/file/manage/upload
