server:
  port: 9051

mysql:
  host: 172.16.17.167
  port: 3306
  dbname: ntcrm_prod
  username: ntcrmProd
  password: ntcrmP@1113

spring:
  data:
    redis:
      host: 172.16.17.167
      port: 6379
      password: nftzcrmR@1113
      database: 13
      front: engjkfxcx_prod_

auth:
  token:
    redis-front: ntcrm_prod_token_

wechat:
  applet:
    version: formal
    envVersion: release

ecc:
  appId: ntwx001
  appSecret: h9r2e2nd5bipf6z
  baseUrl: https://ecc.nftz:8181
  maintenanceListUrl: /publicApi/maintenance/list
  maintenanceDetailUrl: /publicApi/maintenance/detail

epcpv:
  appId: 9902df0531984b9fb68eda78309f2420
  appSecret: BR9P25wO1qmKy9U7759S46AE9A5Yq6HN
  url: http://172.16.17.71:8086/
  allregions: api/v1/pv/project/dim/regions
  allstages: api/v1/pv/project/dim/stages
  total: api/v1/pv/project/total
  capacitytotal: api/v1/pv/project/transformer/capacity/total
  regionstat: api/v1/pv/project/region/stat
  capacitystat: api/v1/pv/project/transformer/region/capacity/stat
  stagestat: api/v1/pv/project/stage/stat
  prolist: api/v1/pv/project/list
  inststat: api/v1/pv/project/inst/capacity/stat

edata:
  baseUrl: http://172.16.17.157:9052

loginAttention:
  sendee: 13632243930,13288012316,13702470083,13250729542,13609089507,18613028815,13560226979,13538985351

file:
  upload:
    upload-url: http://172.16.17.157:9030/resourceManage/file/manage/upload

msg:
  baseUrl: http://172.16.17.156:9002/msg
