server:
  port: 9150

mysql:
  host: 172.18.26.102
  port: 6033
  dbname: ntcrm_dev
  username: ntcrmDev
  password: ntcrmD@1113

spring:
  data:
    redis:
      host: 172.18.26.112
      port: 6379
      password: iot
      database: 11

ecc:
  appId: ntwx001
  appSecret: h9r2e2nd5bipf6z

epcpv:
  appId: 9902df0531984b9fb68eda78309f2420
  appSecret: BR9P25wO1qmKy9U7759S46AE9A5Yq6HN
  url: http://172.18.26.131:8086/
  allregions: api/v1/pv/project/dim/regions
  allstages: api/v1/pv/project/dim/stages
  total: api/v1/pv/project/total
  capacitytotal: api/v1/pv/project/transformer/capacity/total
  regionstat: api/v1/pv/project/region/stat
  capacitystat: api/v1/pv/project/transformer/region/capacity/stat
  stagestat: api/v1/pv/project/stage/stat
  prolist: api/v1/pv/project/list
  inststat: api/v1/pv/project/inst/capacity/stat