mysql:
  host: 172.18.26.102
  port: 3306
  dbname: ntcrm_test
  username: ntcrmTest
  password: ntcrmT@1113

spring:
  data:
    redis:
      host: 172.18.26.112
      port: 6379
      password: iot
      database: 11