server:
  port: 9250

mysql:
  host: 172.16.17.137
  port: 3306
  dbname: ntcrm_test
  username: crm_test
  password: Crm_test@3030

spring:
  data:
    redis:
      host: 172.16.17.137
      port: 6379
      database: 0
      front: engjkfxcx_test_

auth:
  token:
    redis-front: ntcrm_test_token_

wechat:
  common:
    wxUrl: http://172.16.17.147:9011/vcheck
  applet:
    version: trial

ecc:
  appId: ntwx001
  appSecret: h9r2e2nd5bipf6z

epcpv:
  appId: 9902df0531984b9fb68eda78309f2420
  appSecret: BR9P25wO1qmKy9U7759S46AE9A5Yq6HN
  url: http://172.18.26.131:8086/
  allregions: api/v1/pv/project/dim/regions
  allstages: api/v1/pv/project/dim/stages
  total: api/v1/pv/project/total
  capacitytotal: api/v1/pv/project/transformer/capacity/total
  regionstat: api/v1/pv/project/region/stat
  capacitystat: api/v1/pv/project/transformer/region/capacity/stat
  stagestat: api/v1/pv/project/stage/stat
  prolist: api/v1/pv/project/list
  inststat: api/v1/pv/project/inst/capacity/stat

group:
  # 集团领导
  leaderPhones: 13609607618,18602040440,13602838462,13609733222,13318834979,13318818688,18666620068,13924119780,15018777423,13825051033,13570460363,13570377089,15013033335,13380020913,13527798953,13600007818